Public NotInheritable Class AboutBox1

    Private Sub AboutBox1_Load(                                 ' Standard Control event parms...
            sender As Object,
            e As EventArgs
            ) Handles MyBase.Load

        ' Purpose:      Display the application's "About..." window
        ' Process:		Build the title, taking from the Application Configuration, or if that is empty,
        '               from the executable file name. Fill in data from Application Configuration fields.
        ' Called By:    AboutBox1 Load Event
        ' Side Effects: Displays form in a new Window
        ' Notes:        None

        '               <1.059.0> Added Visual Studio "About Box" form to replace MsgBox implementation. Code mostly generated by VS2019

        Dim ApplicationTitle As String
        If My.Application.Info.Title <> "" Then
            ApplicationTitle = My.Application.Info.Title        ' Set the title of the form.
        Else                                                    ' If Title isn't configured in the Application, use the executable's filename instead
            ApplicationTitle = System.IO.Path.GetFileNameWithoutExtension(My.Application.Info.AssemblyName)
        End If
        Me.Text = String.Format("About {0}", ApplicationTitle)

        Me.LabelProductName.Text =
            My.Application.Info.ProductName                     ' Initialize all of the text displayed in the About Box.
        Me.LabelVersion.Text = String.Format("Version {0}", My.Application.Info.Version.ToString)
        Me.LabelCopyright.Text = My.Application.Info.Copyright
        Me.LabelCompanyName.Text = My.Application.Info.CompanyName
        Me.TextBoxDescription.Text = My.Application.Info.Description

    End Sub

    Private Sub OKButton_Click(                     ' Standard Control event parms...
            sender As Object,
            e As EventArgs
            ) Handles OKButton.Click

        ' Purpose:      Close the ABout-Box when user clicks on its "OK" button
        ' Process:		Field event, close form
        ' Called By:    OKButton Click Event
        ' Side Effects: CLoses form/Window
        ' Notes:        None

        Me.Close()                                  ' Dismiss the About Window

    End Sub

End Class
